const int INVALID_ARGUMENTS_COUNT = 201;
const int CANT_OPEN_OR_CREATE_LOG = 202;
const int HOST_ERROR = 203;
const int SOCKET_CREATION_ERROR = 204;
const int SEND_ERROR = 205;
const int RECV_ERROR = 206;
const int LOG_WRITE_ERROR = 207;